### PR TITLE
Ep/new params validator

### PR DESCRIPTION
**Pull request by eliasjpr**
Addresses

https://github.com/amberframework/amber/issues/943
https://github.com/amberframework/amber/issues/770
https://github.com/amberframework/amber/issues/698
https://github.com/amberframework/amber/issues/688

> More tests to come...

### Description of the Change

Introduces Contracts. A contract is an abstraction to handle validation of arbitrary data or object state. It is a fully self-contained object that is orchestrated by the controller.

The Contract macros helps you defining contracts and assists with instantiating and validating data with those contracts at runtime. The `contract` macro will define a Struct with properties and methods. 

Contract macro: 

```crystal
# name of the contract for, 
# key: param key to parse
# block contains param definitions, you can also define other methods as needed.
contract(name, key) do 
...
end
```
Param macro:

Defines properties types and validations for a contract. 
```crystal
  param email : String, length: (50..50), regex: /\w+@\w+\.\w{2,}/
  param! email : String, length: (50..50), regex: /\w+@\w+\.\w{2,}/ # raises error
```

Available validations are:
```crystal
eq - value must qual to
lt - value must be  less than
lte - value must be  less than or equal to
gte - value must be greater than or equal to
gt - value must be greater than
in - Values must be in collection
length - length (objects must respond to size)
regex - regex comparison
```
Example:

```crystal
class FakeController < Amber::Controller::Base
  contract("User") do
    param email : String, length: (50..50), regex: /\w+@\w+\.\w{2,}/
    param name : String, length: (1..20)
    param age : Int32, gte: 58, eq: 24, be: "Age"
    param alive : Bool, be: false
    param childrens : Array(String)
    param childrens_ages : Array(Int32)
    contract("Address", "user.address") do
      param street : String, length: (10..35)
      param city : String, eq: "Jersey City"
      param state : String, in: ["NJ", "NY"]
      param zip_code : String, length: (5..5)
      contract("Location", "user.address.location") do
        param longitude : Int32
        param latitude : Int32
      end
    end
  end
end
```
The example above will create a `User` with properties defined by params with an Address sub struct that can only be accessed via the user. 

Available methods
```
#valid?
#valid!
#error(param : String, value : Any, message : String) 
#errors
#to_h
#validate
```
### Other usages

You can use Contracts outside of controllers by defining a class as follow:

```crystal
struct UserPOCO
    include Contract::Validation
    @raw_params : Amber::Router::Params

   # An instance method will the following signature will be created
   # Key: is a path to the nested param in form of `user.address.city`, `user.address.street`...
   def initialize(raw_params, key : String)
   end
end
```

### Benefits

- Strict Typed objects for params
- Params validation
- Easy/Simple DSL
- Contracts are modular and can be used to outside of controllers (Think POCO Plain Old Crystal Objects)
- Contracts can happen earlier in the request lifecycle not necessarily in a controller this is great if someone wants to validate/fail request earlier.

### Possible Drawbacks

- Breaking change (Removes old param validation
- Generators Need to be updated and tested

### CODE REVIEW

**Comment by robacarp** [comment]
Interesting idea, I like it. Can you show how this is used in a controller action? Eg how is this supposed to be used to read parameters and build or update objects?

**Comment by Sija** [comment]
- Validators should be easily extensible, preferably inheriting from some `abstract class Validator`
- Personally I find confusing and redundant specifying full sub-contract path, like in here:

```cr
contract("User") do
  # ...
  contract("Address", "user.address") do
    # ...
    contract("Location", "user.address.location") do
    # ...
    end
  end
end
```

I'd suggest using just the last path component, detecting the rest automagically:

```cr
contract("User") do
  # ...
  contract("Address", "address") do
    # ...
    contract("Location", "location") do
    # ...
    end
  end
end
```

**Comment by robacarp** [comment]
Nice. This would probably pair well with a PR to Granite to accept a contract directly, rather than `.to_h`-ing the contract.

**Comment by robacarp** [comment]
@Sija has a nice list of features, to which I'd just add that it should be natural for a developer to simply access the params as a raw Hash perhaps a (String => String | Int | Bool or something). This kind of contract / validation on params is going to be really useful _most_ of the time, but there will always be times when the contract paradigm breaks (or is unwanted) and the developer just wants unrestricted access to the params.

**Comment by Sija** [comment]
@robacarp 👍 even better, such a contract could create a `record` (or `struct`) with typed fields, taken from properties defined using DSL - in such a way we'd have compile-time safety + lack of annoying Hash value unions.

**Comment by eliasjpr** [comment]
@robacarp the `context.params` will still exist and be accessible.

**Pull request closed without merging**
