### PR TITLE
Moved wildcard route to bottom by default

### PR DESCRIPTION
**Pull request by elorest**
### Description of the Change

Moves while card static route to the bottom. I've helped multiple people over the last 6 months fix an issue where their route was getting caught by static pipe instead of the route they defined. 

This results in 405 errors. In Rails having a wildcard up top would have even more issues.

### CODE REVIEW

**Comment by eliasjpr** [comment]
A couple of questions: 

- Is there a way we can add a spec to test this case? - Also what would stop someone from moving the wildcard back on top?

**Comment by elorest** [comment]
Same thing as in rails. They know it will break things.

**Comment by elorest** [comment]
Nothing stops them but we shouldn't generate code that could randomly fail.

**Comment by elorest** [comment]
Its likely that we should just address this after we fix the router. All of my manual tests pass for this but for some reason the build specs fail.

**Comment by robacarp** [comment]
This change was included in #432

**Pull request closed without merging**
