### PR TITLE
Adds environment changes to amber deploy

### PR DESCRIPTION
**Pull request by elorest**
### Description of the Change

1. Adds .encryption_key to deployed project so `.production.enc` can be decrypted and used.
1. Adds a flag to not use a local database in docker.
1. Adds the ability to use `environment` files to use any database or redis settings you want.
1. Adds `--environment` option so you could specify staging or something instead of production.

### Benefits

Makes amber deploy more useful.

### CODE REVIEW

**Comment by elorest** [comment]
Any idea why these tests are failing? They all pass locally. No changes here should have broken any tests.

**Comment by faustinoaq** [comment]
Looks like CSRF is failing, maybe we are losing context on Travis, so CSRF token doesn't work.

**Comment by faustinoaq** [comment]
@elorest Are you able to trigger Travis without doing a commit? I mean something like "restart build":

screenshot_20171213_023511

**Comment by elorest** [comment]
Yeah I restarted the build but it still fails... Stupid error too. Doesn't happen on my Macs or linux boxes.

**Comment by elorest** [comment]
Cool it passes now.

**Pull request merged**
