### PR TITLE
Ameba v0.5.0 -> v0.6.0

### PR DESCRIPTION
**Pull request by veelenga**
### Description of the Change

Upgrades Ameba shard. See https://github.com/veelenga/ameba/releases/tag/v0.6.0 for details.

### Benefits

More cool features -> more issues detected -> less bugs -> better code :)

### Possible Drawbacks

The release is pretty new, so you can face some issues. I tried to reduce the false positiveness as much as possible, but if you find something, please report.

### CODE REVIEW

**Comment by faustinoaq** [comment]
I was already trying to enhance some of these code. I think is very useful that ameba can do this automatically :tada:

**Comment by veelenga** [comment]
@faustinoaq, for now, it can only report it. Enhancing is a manual action 😄

**Comment by drujensen** [comment]
@eliasjpr Nice to see you online!  💪

**Comment by eliasjpr** [comment]
Is good to be back :)

**Pull request merged**
