### PR TITLE
Added new exception page

### LINKED ISSUE #770: 400 instead of 500 when params validation failed
### Description

`ValidationFailed` is apparently a client error due to passing invalid params.
Thus, server should response `400 Bad Request` instead of `500 Internal Server Error` when `ValidationFailed` is raised.

### Steps to Reproduce

1. Start a new amber project
2. Generate a scaffold with at least one field
3. POST it without params

**Expected behavior:** 400 Bad Request

**Actual behavior:** 500 Internal Server Error

**Reproduces how often:** always

### Versions

v0.7.2 and master

### Additional Information

I think @faustinoaq is ready to fix this.

### PR DESCRIPTION
**Pull request by faustinoaq**
### Description of the Change

This PR adds a new exception page based on Phoenix one, see: https://github.com/phoenixframework/phoenix/issues/1776

This PR will be required by next `amber watch` PRs

vokoscreen-2018-04-14_18-07-30

### Alternate Designs

Keep basic error pages

### Benefits

- Fixes #770 reported by @c910335
- Add code snippets right in the browser
- Add file navigation
- Add header inspector
- Add Cookies inspector
- Add new awesome design based on Phoenix one with responsive design :sparkles: Thanks to @rstacruz :tada: 

### Possible Drawbacks

[x] Reload (watch) checkbox depends on new `amber watch` configuration (based on `amber_reload.js` without reload pipe)

### CODE REVIEW

**Comment by faustinoaq** [comment]
Some screenshots :heart_eyes: 

screenshot_20180414_132630
screenshot_20180414_080548
screenshot_20180414_052340

**Comment by faustinoaq** [comment]
current error page specs by @marksiemers already cover this :+1:

**Comment by paulcsmith** [comment]
@faustinoaq Just finished up extracting this to a shared lib: https://github.com/crystal-loot/exception_page

You should be able to use it here. I removed the "watcher" stuff since it isn't always needed, but you can hook into the provided methods for customizing the buttons and the javascript that are in the README. Feel free to open PRs for stuff you need in case it doesn't cover everything!

**Comment by faustinoaq** [comment]
@paulcsmith Thanks you so much! Your shard looks very very nice, I gonna use it here now :+1:

**Comment by eliasjpr** [comment]
Lucky already has an exception page base on this code and Amber yet does not this is a bumber :( @paulcsmith @faustinoaq

**Comment by robacarp** [comment]
@faustinoaq given the recent migration of a lot of this code to crystal community repo, should this be closed or merged?

**Comment by eliasjpr** [comment]
@faustinoaq I agree to use the new shard instead you can close this PR and open a new one implementing the shard.

**Pull request closed without merging**
