### PR TITLE
uncomment specs

### PR DESCRIPTION
**Pull request by OpakAlex**
https://github.com/amberframework/amber/issues/1193

### Description of the Change

Fix redirect specs

### Alternate Designs

none

### Benefits

Have more specs

### Possible Drawbacks

none

### CODE REVIEW

**Comment by OpakAlex** [comment]
Just let's see CI errors.

**Comment by OpakAlex** [comment]
@drujensen Can you check my pr? Looks like issue with `Spec.before_suite` It does't run on ci. I am not sure why this happens, because it works for docker, mac. And i am just 3 days with crystal language, maybe you known better how it's possible.

**Comment by drujensen** [comment]
There used to be an issue with `before_suite` but I think this is now fixed in latest crystal version.  I believe this is why we commented these specs out.

**Comment by OpakAlex** [comment]
can we try the last crystal version?

**Comment by OpakAlex** [comment]
don't merge it @drujensen. Let me play a little

**Comment by drujensen** [comment]
Travis is using the latest Crystal 0.34.0 version.

**Comment by OpakAlex** [comment]
but i will try night build too.

**Comment by OpakAlex** [comment]
yes, no luck with stable / night version. @drujensen i think we can use it like tmp solution. i marked it as tmp.

**Comment by OpakAlex** [comment]
@drujensen specs green as tmp fix we can have it.

**Pull request merged**
