### PR TITLE
Fix crystal tool format when creating a new app

### PR DESCRIPTION
**Pull request by epergo**
Fix `crystal tool format` issues **when creating a new Amber project**

Next to this I'll create another PR to fix issues when scaffolding Auth

### CODE REVIEW

**Comment by epergo** [comment]
Added, now the build checks the correct formatting of generated files. Right now the issues are in:

Error: formatting 'src/mailers/dinosaur_mailer.cr' produced changes
Error: formatting 'src/models/animal.cr' produced changes
**Error: formatting 'src/models/user.cr' produced changes** --> Fixed in #798
Error: formatting 'src/sockets/eagle_socket.cr' produced changes
**Error: formatting 'src/controllers/session_controller.cr' produced changes** --> Fixed in #798
Error: formatting 'src/controllers/user_controller.cr' produced changes
**Error: formatting 'src/controllers/application_controller.cr' produced changes** --> Fixed in #798
**Error: formatting 'src/pipes/authenticate.cr' produced changes** --> Fixed in #798

Maybe we can merge this (#797) and #798, and then add this new test plus all files fixed.

WDYT @faustinoaq

**Comment by faustinoaq** [comment]
> Maybe we can merge this (#797) and #798, and then add this new test plus all files fixed. (I can do it)

@epergo Yeah, please, and Thank you! :smile:

We just need this PR to pass Travis before merging (is just a merge requirement) :wink:

**Comment by epergo** [comment]
@faustinoaq I have removed the formatting test to make build pass.

Next I'm going to start working fixing the rest of issues reported when adding the test. Meanwhile #797  and #798  can be merged (if you don't find any issue)

**Comment by epergo** [comment]
I have updated the PR to add a test to check if generated files are correct (formatting-wise) and fixed formatting issues that were pending.

I think that's all.

**Pull request merged**
