### PR TITLE
Change README header to Markdown only

### PR DESCRIPTION
**Pull request by faustinoaq**
### Description of the Change

Make README more compatible with other platforms like [Docker](https://hub.docker.com/r/amberframework/amber/)

### Alternate Designs

No

### Benefits

Fix this:

screenshot_20180111_124534

### Possible Drawbacks

No

### CODE REVIEW

**Comment by marksiemers** [comment]
Good point on the centering.

Can just the `<p align="center">` remain as html and wrap the rest of the markdown or will that not parse?

**Comment by elorest** [comment]
I feel like this was done because all markdown ways of doing it didn't look the same. If everything is the same I say we merge it though.

**Comment by elorest** [comment]
Isn't the Docker readme just a copy of this? Or is it directly linked to the github readme. If the former then just changing it on the docker one makes sense.

**Comment by marksiemers** [comment]
There was a specific commit that looks like the inverse of this: https://github.com/amberframework/amber/commit/07718026480f33fb883788a110c4374835f42561#diff-04c6e90faac2675aa89e2176d2eec7d8

**Comment by faustinoaq** [comment]
> Can just the <p align="center"> remain as html and wrap the rest of the markdown or will that not parse?

Then the README would display a raw `<p align="center">` is some platforms like docker or `crystal docs` itself, WDYT?

> Isn't the Docker readme just a copy of this? Or is it directly linked to the github readme. If the former then just changing it on the docker one makes sense.

Perhaps, we can just modify docker readme and discard this PR.

> There was a specific commit that looks like the inverse of this PR.

@marksiemers Yeah, I did it, and worked fine until I saw https://hub.docker.com/r/amberframework/amber

**Comment by eliasjpr** [comment]
We should just edit the docker Readme instead.

**Comment by drujensen** [comment]
I updated the docker description with these changes.

**Comment by faustinoaq** [comment]
Docker was fixed, this PR is not needed anymore.

Thank you @drujensen !

**Comment by faustinoaq** [comment]
Oh, looks like docker is showing plain html again :sweat_smile: 

https://hub.docker.com/r/amberframework/amber/

**Pull request closed without merging**
