### PR TITLE
[CLI] change the default recipe source URL

### PR DESCRIPTION
**Pull request by damianham**
Issue: https://github.com/amberframework/amber/issues/750
RE: https://github.com/amberframework/recipes/pull/3

Change the default recipe source URL to add the dist folder and support
URLs as a recipe name.

- changes the default recipe source URL
- adds support for a URL as a recipe name

### CODE REVIEW

**Comment by damianham** [comment]
This is ready to be merged - we have changed the recipes repository to match this PR

**Comment by faustinoaq** [comment]
Requires #783 to fix Travis specs

BTW, I already working on `.zip` deployment for amber recipes, and writing some comments about it.

I know @drujensen have some concerns, although I still think recipes is a great Idea,

@drujensen **recipes are not shards, they are just pre-created amber projects**  :sweat_smile: 

The main issue is because we (some of us, including me :wink: ) want to store all _blessed_ recipes in only one repository. This have some pitfalls, although I think I already managed to solved them, just let me publish my ideas (still writing them :sweat_smile: )

**Comment by faustinoaq** [comment]
Hi @damianham I think we should update the URL to:

```
"https://github.com/amberframework/recipes/releases/download/dist/"
```

WDYT?

Ref: https://github.com/amberframework/recipes/releases

**Comment by drujensen** [comment]
@faustinoaq @damianham what is the status on this?

**Comment by faustinoaq** [comment]
@drujensen  This ready and is required by recipes, I'm already working on removing duplicated code from recipes, see: https://github.com/amberframework/recipes/issues/16  I think we should try current recipe implementation by @damianham , then, after some iterations we can try to move it to shards or something better :+1:

**Pull request merged**
