### PR TITLE
Fix dependencies for amber projects using default app template

### PR DESCRIPTION
**Pull request by faustinoaq**
### Description of the Change

Hi, currently we don't specify the version required on dependencies, so when new releases are published, we can find issues like https://github.com/amberframework/quartz-mailer/issues/7

That issue was because I published quartz-mailer `v0.2.1` to pass #370 , My bad 😢 I though dependencies were already fixed.

This PR fixes dependencies to the latest working version for amber `v0.3.0`, However we would need to push again tag `0.3.0` to fix current dependency issues successfully.

### Alternate Designs

Keep current template, being vulnerable to unexpected changes on dependencies.

### Benefits

Ensure the dependencies match to amber release

### Possible Drawbacks

Not That I know

### CODE REVIEW

**Comment by faustinoaq** [comment]
**Warning:** this PR and PRs after quartz-mailer v0.2.1 added [here](https://github.com/amberframework/quartz-mailer/pull/6) never gonna pass because dependency mismatch.

**This PR should be merged and repush `0.3.0` to fix travis builds.**

**Comment by faustinoaq** [comment]
Hi, I gonna apply current merging rules:

> Hi, what are the rules to merge a PR, how many members need to accept the review? :)
> 1) If it’s a bug fix that doesn’t change the interface  then 1.

So, This PR is an emergency bug fix because new projects generated by amber cli are failing showing a dependency mismatch.

**Comment by faustinoaq** [comment]
`v0.3.0` has been republished and is passing https://github.com/amberframework/amber/commits/v0.3.0

**Comment by elorest** [comment]
Thanks. You probably want to update the homebrew formula SHA as well.

**Comment by faustinoaq** [comment]
@elorest please check https://github.com/amberframework/homebrew-amber/pull/5 I don't have merge permission there 😅

**Comment by faustinoaq** [comment]
I fixed `amber-aur` as well 😄

**Comment by elorest** [comment]
There seems to potentially still be an issue. Why is something trying to load a version of kilt that doesn't exist? Why is looking all of the shards in generated shards.yml the currect fix?

**Comment by elorest** [comment]
A breaking change in quartz should be `v0.3.0` instead of `v0.2.1`

**Comment by faustinoaq** [comment]
@elorest I know, but it was just a dependency update. I mean, All I did was updating kilt from 0.3.3 to 0.4.0, is that a breaking change?

The main problem was because we didn't fixed dependencies before, so dependency mismatch was the result. 😅 The dependency version help us to detect shards version problems before push on master.

**Comment by elorest** [comment]
Yeah obviously we'll still occasionally make a breaking change that we didn't intend to be so. Not quite sure why that was a breaking change, have you figured that out?

**Comment by faustinoaq** [comment]
> why that was a breaking change, have you figured that out?

Yeah,It happened  because I updated kilt to 0.4.0 on quartz-mailer but amber kept using 0.3.3. 

Now all is fixed, Amber `v0.3.0` and quartz-mailer `v0.2.0` are using kilt 0.3.3 locked on shard.yml

Meanwhile amber master is using kilt `0.4.0` and dependencies as well.

**Pull request merged**
