### PR TITLE
Fix typo on html code

### PR DESCRIPTION
**Pull request by faustinoaq**
### Description of the Change

- Replace ? by >
- Close tag correctly

Discovered by @mixflame :

> on default setup, views/home/index.cr has a bug in the template, unclosed tag

### Alternate Designs

Nil

### Benefits

Nil

### Possible Drawbacks

Nil

### CODE REVIEW

**Comment by faustinoaq** [comment]
Why is Travis still checking this ? 😅

**Comment by faustinoaq** [comment]
Seems travis is ok:

screenshot_20171024_075140

But Why I still see this?:

screenshot_20171024_075217

**Comment by elorest** [comment]
Just repush it. Travis gets stuck sometimes.

**Comment by faustinoaq** [comment]
> Just repush it. Travis gets stuck sometimes.

@elorest Done! 👍

**Pull request merged**
