### PR TITLE
[Responders] Overloads json method

### PR DESCRIPTION
**Pull request by eliasjpr**
## Description

Removes conditional by overloading the JSON method. 
Ref https://github.com/amberframework/amber/issues/895#issuecomment-400134684

## Benefits
- Simplyfies logic
- Removes Duplication
- Uses Amber::Support::MimeTypes
- It only process the requested mime type

### CODE REVIEW

**Comment by elorest** [comment]
> @robarcarp One benefit is that previously it used to run all the respond formats for each request, for instance, if you had defined the following respond_with, all responder format would process. Not instead only the response format requested will run.

@eliasjpr That's not entirely true. This has been discussed multiple times in other PR's. If you pass a string in that's true but if you pass a proc in it only processed the matching response. This was due to performance issues with procs. @damianham and I put a lot of thought and discussion into this.

Don't refactors and non bug fixes generally require 2 approvals?

**Comment by elorest** [comment]
A couple of the changes I'm fine with but a lot of it just feels like moving code around and renaming stuff arbitrarily. I'm worried that it will introduce an unforeseen bug or change to existing projects.

**Comment by eliasjpr** [comment]
@elorest now it does not process it is a string it skips only small renaming happened and a made use of the Amber::Support::MimeTypes which allowed the class to be cleaned, none of the specs were changed to ensure the same functionality exists

**Comment by elorest** [comment]
Good point on the specs...

As mentioned in slack. Strings are still being rendered with this change. But they're being thrown away and garbage collected immediately instead of used. This doesn't change performance though.

I'm a bit concerned that if I Curled `curl https://domain.com/json_endpoint` it wouldn't return anything in the case that I didn't specify a type or had it defaulted to html since the value was thrown away. In the previous version it feel throw to the first specified if the request didn't match.

**Pull request merged**
