### PR TITLE
Remove logo from app template

### PR DESCRIPTION
**Pull request by dwightwatson**
### Description of the Change
In reference to #1004 - this removes the logo from the app template and the home page views.

### Alternate Designs
These were discussed in #1004.

### Benefits
Solves an issue where the logo would be too large on smaller screens, and removes boilerplate that most developers will remove anyway.

### Possible Drawbacks
People that really like looking at the logo might be disappointed.

### CODE REVIEW

**Comment by faustinoaq** [comment]
> I can't remember for Phoenix, but at least for Rails the home page it ships with isn't actually in the app template - it's just shown if there are no routes registered

Well, I just tried rails and phoenix:

vokoscreen-2018-12-28_08-21-32

vokoscreen-2018-12-28_08-31-55

I think Amber can use some responsive design here :sweat_smile: 

vokoscreen-2018-12-28_08-37-34

**Comment by drujensen** [comment]
@dwightwatson Thanks for doing this!  I like using the bootstrap styles as much as possible so using the one built in would be great.  I think just the logo is fine but would like to hear what others think.

**Comment by dwightwatson** [comment]
I've got this working and looking good, but I might wait until #1007 goes in, as I'll leverage the $primary brand colour that's provided to Bootstrap.

image

**Comment by dwightwatson** [comment]
Yay, thanks!

Was just working on updating the existing generators to output links that are compatible with the Bootstrap navbar too. I'll get that into another PR shortly.

**Comment by elorest** [comment]
Everyone else just has a larger logo that only shows up on the default index page. Why are we choosing to have a small logo in the default layout for all pages?

**Pull request merged**
