### PR TITLE
cli: implement `db create/drop` for sqlite3

### PR DESCRIPTION
**Pull request by nathanj**
When running `amber db create` for an sqlite3 database, amber displays
the error:

  could not determine database name

This can be confusing to the user who doesn't know that `amber db
create` does not need to be run for sqlite3 databases. Display a
friendlier message.

Also implement `amber db drop` to delete the database.

### CODE REVIEW

**Comment by faustinoaq** [comment]
Yeah, I can reproduce this, A workaround is using `amber migrate up`

**Comment by faustinoaq** [comment]
@nathanj Yeah, please add some test for `amber db drop` and `amber db create`(_sqlite_) 😅

**Comment by nathanj** [comment]
I added a test to `init_spec.cr` since I didn't know where else to put it. Let me know if there is a better place

**Comment by eliasjpr** [comment]
@nathanj you can add the specs in `spec/amber/cli/commands/generator_spec.cr`. Please keep the tests clean and readable follow the pattern

**Comment by nathanj** [comment]
Moved the tests and made them a little more spec-like I think (this is my first time using spec).

**Comment by eliasjpr** [comment]
@nathanj Thank you we were just talking about your PR  🎉

**Pull request merged**
