### PR TITLE
Fixed csrf delete for generated scaffolding

### PR DESCRIPTION
**Pull request by elorest**
### Description of the Change

Fixes https://github.com/amberframework/amber/issues/339. 

Also uses link helpers instead of `<a href...>`

### Alternate Designs

At some point we might want to use a helper to generate a form that posts or a JS hack that does it onclick.

### Benefits

Protects from cross site scripting, so that javascript in other tabs can't post valid requests to domains associated with your cookies.

### CODE REVIEW

**Comment by faustinoaq** [comment]
@elorest Can Amber have something like `link "Home", to: HomeController, :index` ?

With params `link "Home", to: HomeController, :index, with: {id: id}`

Instead of using direct links ?

**Comment by elorest** [comment]
@faustinoaq it should be able to. @eliasjpr was working on `url_for` a couple of months ago but it sort of ended up going in a different direction. This will also fix redirect. That information is all available in the router so it wouldn't be that hard to do if you wanted to take a stab at it. It should be in amber core instead of jasper_helpers though since it would be needed by both jasper and amber redirect.

**Comment by elorest** [comment]
`link "Home", to: HomeController, :index, with: {id: id}` syntactically won't work since it has a named params `to:` and then a none named param for `:index`

**Comment by elorest** [comment]
We can improve that later though. This just fixes a bug and should be merged asap in my opinion.

**Comment by elorest** [comment]
Whether is should override GET with DELETE or use POST is a conversation we can have another day. However this is not a security concern since CSRF isn't concerned with man in the middle attacks or copy and pasting links. Please see conversation on issue #339 or read up on CSRF mitigation.
https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)

**Comment by marksiemers** [comment]
@elorest - I agree this should get merged in ASAP. If this gets refactored / more work is done with CSRF and DELETE, we should write some tests around it. AFAIK, this was happening in production and the test suite didn't catch it.

Is that waiting on the ability to do capybara type testing?

**Pull request merged**
