### PR TITLE
web socket missing let declaration

### PR DESCRIPTION
**Pull request by drujensen**
### Description of the Change

When trying to use web sockets, I get a javascript error that the variable `parsed_msg` is not defined.  It is missing the `let` declaration.

### CODE REVIEW

**Comment by drujensen** [comment]
@fridgerator I don't know how to build the `amber.min.js`.  I tried just running `webpack --config webpack.config.js` but it fails with missing node_modules.  I tried installing those modules but babel complained about not being babel-core.

**Comment by faustinoaq** [comment]
@drujensen I found the issue:

1. You need to change `loader: 'babel',` to `loader: 'babel-loader',` on `assets/js/webpack.config.js`

https://github.com/amberframework/amber/blob/master/assets/js/webpack.config.js#L14

2. Next, install npm dependencies in local directory:

```
$ npm install webpack babel-loader babel-preset-es2015
```

3. Next, change directory to `assets/js`:

```
$ cd assets/js
$ ../../node_modules/webpack/bin/webpack.js --config webpack.config.js
Hash: c1fcf15885b2cf61f0ab
Version: webpack 3.8.1
Time: 1368ms
       Asset     Size  Chunks             Chunk Names
amber.min.js  3.57 kB       0  [emitted]  main
   [0] ./amber.js 8.09 kB {0} [built]
```

And `amber.min.js` is Done!

**Comment by faustinoaq** [comment]
Maybe we should add a `package.json` to built it easier:

So, `package.json`:

```
{
  "name": "amber",
  "version": "0.3.0",
  "description": "Front-end script for Amber Framework",
  "private": true,
  "author": "Amber",
  "license": "MIT",
  "scripts": {
    "build": "cd assets/js && webpack --config webpack.config.js"
  },
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.1",
    "webpack": "^3.8.1"
  }
}
```

Then, `npm install && npm run build`:

```
➜  amber git:(master) ✗ npm install

> uglifyjs-webpack-plugin@0.4.6 postinstall /home/main/Projects/amber/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

added 347 packages in 11.354s
➜  amber git:(master) ✗ npm run build

> amber@0.3.0 build /home/main/Projects/amber
> cd assets/js && webpack --config webpack.config.js

Hash: c1fcf15885b2cf61f0ab
Version: webpack 3.8.1
Time: 1444ms
       Asset     Size  Chunks             Chunk Names
amber.min.js  3.57 kB       0  [emitted]  main
   [0] ./amber.js 8.09 kB {0} [built]
```

**Comment by faustinoaq** [comment]
Hi, I published #372 including front-end configuration to build `amber.min.js`

**Pull request merged**
