### PR TITLE
Upgrade to Crystal 0.28.0

### PR DESCRIPTION
**Pull request by bcardiff**
I found the following changes needed to upgrade to the upcoming Crystal 0.28.0.

If some macro `compare_versions` are added it should be possible to support current versions as well.

Feel free to extract these changes and close the PR if you prefer to handle the migration in a specific way.

### CODE REVIEW

**Comment by bcardiff** [comment]
Note that db related shards are also in the process of been updated for Crystal 0.28.0.

**Comment by elorest** [comment]
Thank you.

**Comment by bcardiff** [comment]
FYI the crystal-pg/mysql/sqlite3 shards are already released with 0.28.0 support

**Comment by elorest** [comment]
Thanks a lot for your help on this. Upgrading proved more difficult than most but it's been accomplished now.

**Pull request closed without merging**
