### PR TITLE
Improve column names in `amber pipelines`

### PR DESCRIPTION
**Pull request by docelic**
This simple commit replaces 'amber pipelines' columns named "pipe" and "plug" with "pipeline" and "pipe".

This describes the values contained in each column more accurately.

### CODE REVIEW

**Comment by robacarp** [comment]
@docelic thanks! Would you mind posting a screenshot?

**Comment by faustinoaq** [comment]
> Would you mind posting a screenshot?

screenshot_20180409_091435

@robacarp ^ :smile:

**Comment by eliasjpr** [comment]
Failing spec  https://travis-ci.org/amberframework/amber/jobs/364273092#L614

**Comment by robacarp** [comment]
Thank you for cleaning this up @docelic

**Pull request merged**
