### PR TITLE
[CLI] Adds support for generating pages

### PR DESCRIPTION
**Pull request by davidpatters0n**
### Description of the Change

Address: https://github.com/amberframework/amber/issues/671

### Alternate Designs
None 

### Benefits
Allows developers to run `amber g page About`

### Possible Drawbacks
None

### CODE REVIEW

**Comment by faustinoaq** [comment]
@davidpatters0n Thank you for this nice contribution!

Can we add a `page` generator as well :sweat_smile:

Right now is just `amber g view About`, but is just the view, so I can't add quickly a new page without touching the code

Currently with this PR:

```sh
# 1. Generate src/views/about_view.slang
amber g view About

# 2. Create src/controllers/about_controllers.slang
amber g controller About

# 3. Edit controller to render about view
nano src/controllers/about_controllers.slang

# 4. Edit config/router.cr to point /about path to AboutController :index
nano config/router.cr
```

With proposed `amber g page About`

```sh
# Generate new view, controller and update the new path to router file
amber g page About
```

Lucky framework can do something similar using  `lucky gen.page About`

@amberframework/contributors WDYT?

**Comment by faustinoaq** [comment]
BTW, I think we can change `raise "Template not found"` by:

```crystal
CLI.logger.error "Template not found", "Generate", :light_red
```

less verbose, more clean

**Comment by davidpatters0n** [comment]
@faustinoaq - Sure I'll make this amendment later on today. 👍 thanks for the feedback

**Comment by eliasjpr** [comment]
@faustinoaq Lucky follows a different naming conventions. I am fine not adding a Page generator also that seems that can be addressed in a separate PR.

**Comment by elorest** [comment]
@faustinoaq A new page should be added with

`amber g controller About about:get` with existing generators.

**Comment by faustinoaq** [comment]
@eliasjpr @elorest Yeah, I wanted to review this a bit more but I see it just got merged (and reverted) :sweat_smile:

**Pull request merged**
