### PR TITLE
Centered logo README

### PR DESCRIPTION
**Pull request by faustinoaq**
### Description of the Change

Add new header based on https://github.com/veelenga/ameba/blob/master/README.md by @veelenga 

screenshot_20171102_151431

### Alternate Designs

No

### Benefits

Beautiful design 😄 

### Possible Drawbacks

No

/cc @amberframework/contributors

### CODE REVIEW

**Comment by faustinoaq** [comment]
The Amber's description was taken from https://www.crystalvaults.com/crystal-encyclopedia/amber

**Comment by marksiemers** [comment]
@faustinoaq - Overall, I think this looks good. My only issue is that if this is all the content "above the fold" (what you see before scrolling), then it doesn't say much about the amber framework specifically.

"Fun. Statically Typed, High Performance" can describe a lot of Crystal apps.

I think we should have something a little more specific, so whoever sees the readme knows what Amber is and why they would use it.

The website has: "Amber is a web application framework written in Crystal inspired by Kemal, Rails, Phoenix and other popular application frameworks."

That sounds good for a description, but may be too long to go right under the logo.

I like "Fast as Phoenix, Easy as Rails"

It's been pointed out that Phoenix isn't actually that fast, but that is the perception it has. I think if we said "Faster than Phoenix, Easy as Rails" then we might get some blowback.

Maybe "Production grade Web Applications out of the box"

**Comment by veelenga** [comment]
Be ware that breaks layout of readme generated by `crystal docs`. I'm not sure if this is relevant for Amber

**Comment by faustinoaq** [comment]
@veelenga Does Crystal Markdown support embedded HTML?

**Comment by faustinoaq** [comment]
> I think if we said "Faster than Phoenix, Easy as Rails" then we might get some blowback.

Is it good or bad?

screenshot_20171103_114933

**Comment by faustinoaq** [comment]
@eliasjpr I just saw your comment on gitter channel 😅 

> Amber makes building web applications simply fast, reduced bugs, and enjoyable without sacrificing performance.

So:

screenshot_20171103_115219

Maybe the Amber meaning is misleading? 😅 

_one of the world’s oldest and most coveted treasures, a “Gold of the Sea” intrinsically formed by light and life_

**Comment by veelenga** [comment]
> Does Crystal Markdown support embedded HTML?

Nope:

```crystal
 Markdown.to_html("<a href='https://'></a>")
 => "<p>&lt;a href='https://'>&lt;/a></p>"
```

I read somewhere Crystal sanitizes left bracket for security reasons.

**Comment by marksiemers** [comment]
@faustinoaq How about:

Amber makes building web applications fast, simple, and enjoyable - with fewer bugs and blazing fast performance.

**Comment by marksiemers** [comment]
@faustinoaq - Regarding the "Faster than Phoenix, Easy as Rails" statement - I just think they will both require some backup (maybe directly in the readme, in a section further down).

For "Faster than Phoenix" - If the new round of TechEmpower benchmarks come out, we can (hopefully) point to those, assuming the numbers are faster than Phoenix.

Fore "Easy as Rails" - that is more subjective, but we could so a sample of scaffolding a blog with user authentication via command line - that is a pretty good use case.

**Comment by eliasjpr** [comment]
@marksiemers those are bold statements. `Faster than Phoenix` I don't want to start a battle royale with a more established community. I also feel it goes against part of our philosophy `Humility`

**Comment by marksiemers** [comment]
@eliasjpr - Agreed. 

The Crystal tagline "Fast as C, Slick as Ruby" was the inspiration for the style "Blank as This, Blank as That"

If a comparison is valuable, something complementary could work better than "fightin' words":

"Fast **as** Phoenix, Easy as Rails"
"Rails Productivity with Phoenix Speed"

Although, we could consider avoiding comparisons altogether. 

A different approach could be taken:
"Fast. Easy. Enjoyable"
"Enjoyable. Compiled. Performant."
"Coder Happiness with Compiled & Concurrent Performance"
"Clear, Concurrent, Compiled Code"

**Comment by marksiemers** [comment]
@amberframework/core-team 

I vote for these:

> Fun Syntax. Reliable Static Typing. Compiled Speed.

> Amber makes building web applications fast, simple, and enjoyable - with fewer bugs and blazing fast performance.

**Comment by faustinoaq** [comment]
@marksiemers Done! 👍 

screenshot_20171103_192718

**Pull request merged**
