### PR TITLE
Deploy using Travis

### LINKED ISSUE #877: Generate Amber executables using CI
### Description

Currently we need to compile amber from source, would be nice to generate executables and include them on release page. (idea suggested by @conradwt)

### Steps to Reproduce

Not applicable

### Versions

Amber v0.7.2

### Additional Information

We can use something like Crystal (1) or Scry (2)

1. https://github.com/crystal-lang/crystal/releases
2. https://github.com/crystal-lang-tools/scry/releases

### PR DESCRIPTION
**Pull request by faustinoaq**
# DO NOT MERGE YET! :warning: 

~~Please see: https://github.com/faustinoaq/amber/releases (testing this setup on my fork, new "test" releases will be published soon :smile: )~~ Not published yet! I found some issues with `--static` flag on Linux deployment, I'm missing some static libraries, I need to fix this first.

Why?

` crystal build src/amber/cli.cr -s --release --static` still may throw errors because missing `-dev` packages

### Description of the Change

We can use Travis to deploy Amber like Scry and Crystal does.

### Alternate Designs

Use CircleCI

### Benefits

Fixes #877 (suggested by @conradwt :+1: )

### Possible Drawbacks

Maybe we should test it before an official release /cc @elorest

### CODE REVIEW

**Comment by faustinoaq** [comment]
I gonna test it before in my own fork :+1:

**Comment by faustinoaq** [comment]
Useful resource here: https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A

**Comment by eliasjpr** [comment]
will this tag releases on GitHub as well?

**Comment by faustinoaq** [comment]
@eliasjpr It could be, but I think we should manage the releases, manually using crelease, WDYT?

/cc @elorest

**Comment by faustinoaq** [comment]
There is some issues with osx

Ref: https://github.com/travis-ci/travis-ci/issues/6307

Ref: https://github.com/travis-ci/travis-ci/issues/1875

**Comment by faustinoaq** [comment]
@elorest @eliasjpr maybe we include Crelease here and automate the release process, WDYT?

**Comment by elorest** [comment]
I'm fine automatic releases in theory. It just seems like a lot of work to get it to behave properly vs 30 seconds to run a script (crelease) whenever we decide to release. In crystal it's a lot more useful because they need to generate binaries for multiple architectures.

The most complex part of our current releases are in order of descending difficulty:

1. Validating that there are not serious breaking changes or bugs.
1. Dependency Validation.
1. Updating homebrew and other package managers.
1. Releasing and Tagging.

**Comment by eliasjpr** [comment]
If we are manually releasing why build binaries?

**Comment by elorest** [comment]
@eliasjpr I don't think we are building binaries are we?

**Comment by conradwt** [comment]
@eliasjpr The reason being that the user of Amber Framework shouldn't have to perform the following steps:

```
git clone https://github.com/amberframework/amber.git
cd amber
git checkout stable
make
sudo make install
```

The above steps should only be required for contributors/developers of the framework instead of people wanting to build that awesome site of the future.  In short, I think that the on boarding user experience for using Amber should be streamlined and inviting for users new to both Amber and Crystal.

**Comment by eliasjpr** [comment]
@ChangJoo-Park for that matter user can install from brew which performs those steps automatically and I believe we have AUR package for Arch based linux and Linux brew for Debian and others.  The steps above are more for a build from source. Also I dont know how the changes here are addressing this specific need since this is CI based. Am I missing something?

@elorest I think the changes here are building binaries using travis. 

Overall I think we should split the CLI from the Amber Framework (lib) since the CLI is what needs to compile,

**Comment by faustinoaq** [comment]
@eliasjpr This PR is very useful to point AUR package to the published executable on release page.

Currently AUR package is building amber from source, so some unexpected issues related to user environment can break the build.

Also, and most important, not all devs use macOS/ArchLinux, in fact most devs use Debian/Ubuntu, so they still need to compile from source like @conradwt said.

**Comment by faustinoaq** [comment]
I think We can skip automated released for now, We can try to implement them in a new PR :+1:

**Comment by faustinoaq** [comment]
@eliasjpr BTW, Why did you mention to @ChangJoo-Park ? I guess you meant @conradwt :sweat_smile:

**Comment by faustinoaq** [comment]
I'm already testing this on my fork https://github.com/faustinoaq/amber

A bunch of test Releases, will be available on https://github.com/faustinoaq/amber/release soon :wink:

**Comment by conradwt** [comment]
@faustinoaq Nice work!!!!

**Comment by eliasjpr** [comment]
For debían and Ubuntu users we can provide a simple sh script that installs amber without running thru the steps. I recently installed amber on Ubuntu and just had to run ‘brew install amber’ 🤷🏻‍♂️

If you can get this working and it does not add overhead to maintenance I’ll say 🙌🏻

**Comment by faustinoaq** [comment]
> If you can get this working and it does not add overhead to maintenance I’ll say 🙌🏻

Yeah, no problem, I can get this working with zero maintenance overhead :wink: 

This PR just gonna append the bundle to release page only if stable branch is updated and a tag is released.

**Comment by faustinoaq** [comment]
Hi again :sweat_smile: 

I'm having several issues with macOS:

```
Unhandled exception: SSL_connect: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (OpenSSL::SSL::Error)
```

Ref: https://travis-ci.org/amberframework/amber/jobs/394717269#L2741

------------------

```
FATAL:  database files are incompatible with server
DETAIL:  The data directory was initialized by PostgreSQL version 9.5, which is not compatible with this version 9.6.5.
```

Ref: https://travis-ci.org/amberframework/amber/jobs/394717270#L2721

-------------------

```
Unhandled exception:  (DB::ConnectionRefused)
```

Ref: https://travis-ci.org/amberframework/amber/jobs/394717270#L2792

-------------

Any idea How to fix this issues?

PS: I'm not a macOS user :sweat_smile: 

/cc @drujensen @bcardiff

**Comment by faustinoaq** [comment]
Already testing https://github.com/faustinoaq/amber/pull/1 :tada:

**Comment by conradwt** [comment]
I’ll create a Portfile and build a binary executable for MacPorts as I don’t use Homebrew on my system.  Also, I’ll see if I can automate this as well.

**Comment by faustinoaq** [comment]
I got it!, now `postgres` and `redis` are running on macOS successfully, now I'm getting this:

```
Unhandled exception: SSL_connect: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version (OpenSSL::SSL::Error)
```

Has anyone seen this before? :sweat_smile: 

Ref: https://travis-ci.org/amberframework/amber/jobs/394834171#L2748

**Comment by faustinoaq** [comment]
I'm trying to fix openssl on macOS, what a mess! :sweat_smile:

**Comment by faustinoaq** [comment]
`openssl` on osx has been fixed, now I'm getting a postgres connection error:

```
Error connecting to 'localhost:5432': Connection refused 
```

Ref: https://travis-ci.org/amberframework/amber/jobs/394942006#L2845

/cc @drujensen

**Comment by bcardiff** [comment]
@faustinoaq that’s why i usually add a ci branch rule. To stress the ci despite PR :-)

**Comment by faustinoaq** [comment]
OSX CI is working just fine now :tada: :sparkles: :smile: 

https://travis-ci.org/amberframework/amber/builds/394969788 :100: 

(_osx: still a small random bug on createuser waiting for a pg initialization_)

**Comment by faustinoaq** [comment]
> This is great! It would be good see how we can map the released binaries to Homebrew

Please be aware that amber is compiled dynamically on macOS, so, some deps libs are still required.

You can use `ldd $(which amber)` to see what libs are required/missing

**Comment by conradwt** [comment]
@faustinoaq I have a couple of questions regarding Amber:

-  Why isn’t SQLite3 the default database?

-  Why is Redis required?

I currently work as a Ruby on Rails mentor for The Firehose Project.  Thus, I spend quite a lot time with environment setup and SQLite3 would be absolutely fastest way to get a student up and going to learn the basics of <insert your web framework here>.

Then, as they move forward in their training, one can introduce a production ready database like PostgreSQL, MySQL, and so on.

**Comment by conradwt** [comment]
@faustinaq Should I create another issue or proposal for the MacPorts work and someone can simply assign that task to me?  

I should be able to create it over the weekend as the work week only allowed for light MacPorts research and it appears to be a straight forward process.

**Comment by eliasjpr** [comment]
@conradwt these are very good questions. 

- Why isn’t SQLite3 the default database? We have built amber with a production ready mindset. While Sqlite3 is a great prototype options most developers uses either MySQL or Postgress to publish an app. I know we are making a lot of assumption. 
- Why is Redis required? Redis is a required dependency for managing sessions. I will see how we can remove this dependency and default to an in memory store for sessions.

**Comment by faustinoaq** [comment]
@conradwt Nice questions :+1: 

@eliasjpr Nice responses :100: 

> Should I create another issue or proposal for the MacPorts work and someone can simply assign that task to me?

@conradwt I just opened #890 and already sent you a invitation to assign you the issue,

Thank you for contribute! very appreciated :+1: :smile:

**Comment by faustinoaq** [comment]
> I just opened #890 and already sent you a invitation to assign you the issue,

@conradwt Assigned! :+1:

**Comment by conradwt** [comment]
@faustinoaq Great, thanks!!!!

**Comment by faustinoaq** [comment]
> If this is working we should merge it since it does not affect the Amber Library.

@eliasjpr @drujensen This is not working yet, I found some issues with `--static` flag, we're missing some dependencies, I'll try to fix it this weekend :sweat_smile:

**Pull request closed without merging**
