### PR TITLE
Crystal next support

### PR DESCRIPTION
**Pull request by veelenga**
https://github.com/crystal-lang/crystal/releases/tag/0.24.0

**Shouldn't be merged before Crystal official release and before other dependencies are upgraded.**

Depends on:

* https://github.com/jeromegn/slang/pull/28
* https://github.com/crystal-community/icr/pull/72
* https://github.com/mosop/teeplate/pull/7
* https://github.com/samueleaton/sentry/pull/15

Also requires upgrades in:

* https://github.com/mosop/cli
* https://github.com/will/crystal-pg/
* https://github.com/crystal-lang/crystal-mysql

### CODE REVIEW

**Comment by marksiemers** [comment]
Right now, Crystal 0.24.0 is not going to be a stable/official release. Waiting for 0.24.1

**Comment by marksiemers** [comment]
Will reopen after repo cleaning. I have a local copy of this branch, and it still exists in @veelenga 's fork.

**Comment by veelenga** [comment]
PRs are actually designed to prevent you loosing your data locally. Don't see any reason to close it. But anyway if Crystal 0.24 is not going to be stable, better to prepare new PR for future release ;)

**Comment by marksiemers** [comment]
@veelenga - We were attempting to get the total repo size down (from about 8MB) - part of that process meant closing all PRs and deleting all branches.

It didn't quite work - git history on github is a stubborn thing (which is a feature I suppose)

**Comment by faustinoaq** [comment]
Can we reopen it?

For some reason now arch linux is using crystal 0.24.0 on community repo and now I'm getting this error:

```
Error in src/ruby2crystal.cr:1: while requiring "../config/*"

require "../config/*"
^

in config/application.cr:1: while requiring "amber"

require "amber"
^

in lib/amber/src/amber.cr:5: while requiring "secure_random": can't find file 'secure_random' relative to '/home/main/Projects/ruby2crystal/lib/amber/src'

require "secure_random"
```

Well, At least I know how to fix it temporally 😅

**Comment by faustinoaq** [comment]
@veelenga Can we reopen this? Looks like crystal `v0.24.1` will be released very soon https://github.com/crystal-lang/crystal/pull/5358#issuecomment-350682888

**Pull request closed without merging**
