### PR TITLE
Update to Crystal 0.24.1

### PR DESCRIPTION
**Pull request by bcardiff**
This PR is built on top of https://github.com/amberframework/amber/pull/453 with some addional changes I notice that are needed for 0.24.1

Note that full support for 0.24.1 depends on other deps to be updated as #358 state. And there are PR/WIP on most of them.

### CODE REVIEW

**Comment by faustinoaq** [comment]
From https://github.com/amberframework/amber/pull/453#issuecomment-353674848 :

> They will need to publish the assets for me to update the docker image to 0.24.1. for example, https://github.com/crystal-lang/crystal/releases/download/0.24.0/crystal-0.24.0-2-linux-x86_64.tar.gz

So we depend on `crystalllang/crystal:0.24.1` and `drujensen/crystal:0.24.1` to be able to pass Travis.

**Comment by drujensen** [comment]
@faustinoaq I thought we already moved away from my docker image. How are you installing 0.24.1 without the release on linux?  From source?

**Comment by faustinoaq** [comment]
> I thought we already moved away from my docker image

@drujensen Oh, I thought your docker-repo was still needed [here](https://github.com/amberframework/amber/blob/master/Dockerfile#L1) and [here](https://travis-ci.org/amberframework/amber/jobs/320101462#L462) and [here](https://travis-ci.org/amberframework/amber/jobs/320101463#L474) 😅

**Comment by drujensen** [comment]
@bcardiff I updated the drujensen/crystal docker image to 0.24.1.  Looks like there is a conflict in this branch.  Will you be able to resolve it?

**Comment by elorest** [comment]
I merged this in.

**Pull request merged**
