### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by ashishbista**
Fixes amberframework/homebrew-amber/issues/7

Updating dependencies so that Amber works with Crystal 0.36.1.

### CODE REVIEW

**Review by robacarp — APPROVED** [review]

**Comment by ashishbista** [comment]
@robacarp Sorry, I didn't realize force pushing to my branch would undo your approval. Could you please review it again. Thank you!

**Comment by contentfree** [comment]
Additionally, does anyone know who is responsible for the amberframework/amber tap in homebrew? I assume it needs to be updated too so that this updates there.

**Review by eliasjpr — APPROVED** [review]

**Review by robacarp — APPROVED** [review]

**Review by Sija — APPROVED** [review]

**Comment by acook** [comment]
Does anything else need to be done to get this merged so Amber will build again?

**Comment by alex-lairan** [comment]
I think it's all good to merge.

Waiting for maintainers to merge this one, I need it too :D

**Pull request merged**
