### PR TITLE
Update tagline

### PR DESCRIPTION
**Pull request by marksiemers**
This new tagline came up during a gitter conversation. @eliasjpr and I like it.

What does the rest of the @amberframework/core-team think?

### CODE REVIEW

**Comment by marksiemers** [comment]
screen shot 2017-11-04 at 8 42 17 pm

**Comment by elorest** [comment]
I for one love it.

**Comment by faustinoaq** [comment]
I like it 👍

**Comment by marksiemers** [comment]
I don't have the access to merge. Does someone want to merge this?

**Pull request merged**
