### PR TITLE
Removes slash from before resources.

### LINKED ISSUE #1082: routes resources  without / prefix
### Description

```crystal
routes :api, "/api" do
    resources "/pets", PetController
  end
```
this works well , but not work without "/" prefix. 

add "/" prefix to scope is not bad.
but to resources is not acceptable.

### PR DESCRIPTION
**Pull request by pynixwang**
Make this dsl more "domain", not just append path.

fix #1082

### CODE REVIEW

**Comment by pynixwang** [comment]
I remove prefix from 8538e6c ,but generated app also get it.

**Comment by pynixwang** [comment]
it passed on local, maybe generated app not use fixed code. it use master branch?

**Comment by pynixwang** [comment]
`resources :pets` can be done by this way.

**Comment by elorest** [comment]
Please fix the tests. I just released a new version of amber and both it and master pass. If you look at the .travis.yml file you can see how the specs are being run.

**Comment by pynixwang** [comment]
I will try.

**Comment by pynixwang** [comment]
yeh, pass!

**Comment by elorest** [comment]
@robacarp Do you see any issues with merging this?

**Comment by pynixwang** [comment]
this pr cause `amber routes` fail to match.

**Comment by pynixwang** [comment]
routes info should get from `Amber::Server.router.routes_hash`

**Comment by pynixwang** [comment]
but `Amber::Server.router.routes_hash` need to compile app.

maybe should parse `routes.cr` and get from `AST`

**Pull request merged**
