### PR TITLE
Move build test to its own file and test more aspects of build

### PR DESCRIPTION
**Pull request by marksiemers**
See https://github.com/amberframework/amber/pull/348

A big refactor of the specs was done before merging #348 - It was easier to just redo these changes.

### CODE REVIEW

**Comment by marksiemers** [comment]
@amberframework/core-team - These tests will still fail. Based on our discussion of CSRF in the generated controller spec files, it sounds like a fix could go in that will make the tests pass.

In order to get them to pass, there is an issue that needs to be resolved in `amber-spec` though.

It is fixed here: https://github.com/amberframework/amber-spec/pull/7
But that line change (or other fix) could be incorporated into the other changes happening with amber-spec.

**Comment by marksiemers** [comment]
Another error has been uncovered. I'm going to comment some lines out, but this will be good to address for a next release (getting this integration test to pass with everything):

```
 158.     # Cast params and set fields.
 159.     private def cast_to_field(name, value : Type)
 160.       if !value.nil?
 161.         case name.to_s
 162.
 163.           when "user_id"
 164.
>165.               @user_id = value.to_i64
 166.
 167.
 168.           when "post_id"
...
undefined method 'to_i64' for Array(JSON::Type) (compile-time type is (Array(JSON::Type) | Bool | Float64 | Hash(String, JSON::Type) | Int64 | String))
```

The full trace is here: https://www.zerobin.net/?85f41ce66ae44756#jqdAoilihS2iB+bX7Kdx+poCoa6lIYc17XDKnr3nm+A=

**Comment by drujensen** [comment]
I think this was fixed [here](https://github.com/amberframework/granite-orm/pull/85).  Need to release granite-orm

**Comment by marksiemers** [comment]
It seems this integration test will be good at catching bugs introduced by dependencies and/or breaking changes.

**Comment by marksiemers** [comment]
You'll see that I gutted a lot of what is being tested: https://github.com/amberframework/amber/pull/354/commits/21b1083ed8d3972a639024f90ebb8856e9c76b6f

If issues are resolved (like @drujensen mentioned), then some of these can be added back in.

The thing that needs to be fixed is the `amber-spec` constant issue. The thing that can be fixed is the with granite and the JSON casting thing.

@drujensen A couple questions:
1. For the `amber-spec` - any chance a change will go in to address the same thing as amberframework/amber-spec#7
1. For the granite fix, that is waiting on a release? Any chance of that happening before the next Amber release?

**Comment by drujensen** [comment]
@marksiemers yeah, i will release it tonight when i get a chance

**Comment by eliasjpr** [comment]
I can release if that's okay with you @drujensen

**Comment by drujensen** [comment]
Please do. I’m swamped.

**Comment by drujensen** [comment]
I released Granite 0.7.6.  This should fix the issue with `to_i64` against a `JSON::Type`.

**Comment by marksiemers** [comment]
@amberframework/core-team - It looks like the change to amber-spec may have an issue. The error in this test is `undefined method 'get'`:
```
"Error in line 1: while requiring \"./spec/controllers/animal_controller_spec.cr\"\n\nin spec/controllers/animal_controller_spec.cr:18: \e[1mundefined method 'get'\e[0m\n\n      get \"/animals\"\n      \e[32;1m^~~\e[0m\n\n"
```

**Comment by marksiemers** [comment]
If #381 goes in, this can likely be closed, it includes these changes plus more.

**Comment by marksiemers** [comment]
Done in #381

**Pull request closed without merging**
