### PR TITLE
Updates for Crystal 0.29

### PR DESCRIPTION
**Pull request by bcardiff**
Tracking updates to support Crystal 0.29:

- [x] There a couple of relative paths used in `require`s that needs to be fixed for Crystal 0.29.0
- [x] Fix deprecation warnings for Time.now
- [ ] Ameba reference updated
  - [x] Waiting on merges: https://github.com/veelenga/ameba/pull/106 and https://github.com/veelenga/ameba/pull/108
  - [x] [Ameba 0.10 is released](https://github.com/veelenga/ameba/releases/tag/v0.10.0)
- [ ] Granite reference updated
  - [x] https://github.com/amberframework/granite/issues/337 fixed

### CODE REVIEW

**Comment by bcardiff** [comment]
@elorest Sure! that is effectively what the PR is doing, fixing the relative paths.

In https://github.com/crystal-lang/crystal/pull/7758 the requirement algorithm was fixed/improved. The current (wrong) relative path in this repo will stop working. Up to 0.28 the algorithm manages to match the expected file thanks to a specific layout of the directories.

**Comment by robacarp** [comment]
Thanks @bcardiff :)

**Comment by bcardiff** [comment]
Nothing more to be done in this PR from my side 🚀 

FYI To fully support crystal 0.29.0 dev environment a bump in ameba will be needed.

**Comment by nsuchy** [comment]
@bcardiff If you have time could you look at https://github.com/amberframework/granite/issues/337 there's an issue in the JSON Serialization with Granite caused by changes in Crystal's update

**Comment by drujensen** [comment]
@bcardiff I released Granite 0.16.0 and sent a PR to your branch to update a couple other shards.

**Pull request merged**
