### PR TITLE
Add support for crystal v0.24.1

### PR DESCRIPTION
**Pull request by faustinoaq**
### Description of the Change

Add support for crystal for v0.24.1

### Alternate Designs

Remove compatibility with v0.23.1

### Benefits

I think v0.23.1 is still relevant

### Possible Drawbacks

No

### CODE REVIEW

**Comment by wontruefree** [comment]
0.24.0 was auto upgraded on a few of my systems.
I would like to follow the upgrade.  I think there are a few PRs on supporting projects.

**Comment by robacarp** [comment]
It might be simpler to update the code to the 24.1 syntax and switch on monkeypatching the 23.1 classes. Random/secure should be easy enough to backport, and that covers several of the changes made here.

**Comment by elorest** [comment]
I think when 24.1 comes out we should just add support for it and mark 0.24.1 as the minimum version that amber 0.5.1 supports.

I don't think we should try supporting 2 versions of crystal. When 0.24.1 officially comes out most people will only have it.

**Comment by drujensen** [comment]
@faustinoaq They will need to publish the assets for me to update the docker image to 0.24.1.  

for example, `https://github.com/crystal-lang/crystal/releases/download/0.24.0/crystal-0.24.0-2-linux-x86_64.tar.gz`

**Comment by wontruefree** [comment]
Is there documentation on the syntax changes of the 24.1 release?

**Comment by faustinoaq** [comment]
Moved to #454

**Pull request closed without merging**
