### PR TITLE
Fixes slang indentation on scaffolding template

### LINKED ISSUE #613: Default slang template issues on v0.6.5
### Description

I tested amber `v0.6.5` and found some uncomfortable issues:

screenshot_20180202_092303

screenshot_20180202_092325

Looks like generated Slang has wrong  indentation:

screenshot_20180202_092430

screenshot_20180202_092456

### Steps to Reproduce

1. Create a new amber project
2. Scaffold something
3. See some `.slang` files wrong indented 

**Expected behavior:** Good slang indentation that generate good html

**Actual behavior:** bad slang indentation == generate bad html

**Reproduces how often:** 100%

### Versions

`v0.6.5`

### Additional Information

An user can solve this manually editing the `.slang` files in a project. Also looks likeit can be solved by chaging `-%>` to `%>` in default templates.

### PR DESCRIPTION
**Pull request by faustinoaq**
### Description of the Change

Fixes #613 

### Alternate Designs

No

### Benefits

Fixes #613 

### Possible Drawbacks

No

### CODE REVIEW

**Comment by faustinoaq** [comment]
I tested it and generated ECR and HTML looks good 👍 

screenshot_20180202_093103

screenshot_20180202_093137

Some extra new lines but I think this is better that #613 and #602

**Comment by faustinoaq** [comment]
HTML looks good too:

screenshot_20180202_094032

screenshot_20180202_094103

Fixing #602 definitively:  

screenshot_20180202_094257

screenshot_20180202_094345

**Comment by drujensen** [comment]
We should do a patch release for this. WDYT?

**Comment by faustinoaq** [comment]
> We should do a patch release for this. WDYT?

I think so 😅

**Comment by drujensen** [comment]
@faustinoaq why is there extra lines?  This used to work.

**Comment by drujensen** [comment]
@faustinoaq can you add back the `-%>` so the extra lines will not be added?

**Comment by faustinoaq** [comment]
> @faustinoaq why is there extra lines? This used to work, right?

No, it didn't. Remember #602 😅

**Comment by eliasjpr** [comment]
lets wait to see if we can get a lease the current PRs in and do another release over the weekend. WDYT?

**Comment by faustinoaq** [comment]
> @faustinoaq why is there extra lines? This used to work, right?

The browser fixed the bad html, it was lying us:

screenshot_20180131_145546

screenshot_20180131_145728

screenshot_20180131_145814

screenshot_20180131_150616

**Comment by drujensen** [comment]
ok, so this is a bug in slang?

**Comment by faustinoaq** [comment]
> ok, so this is a bug in slang?

I think so

> By removing the eol, this is a work around?

kinda

**Comment by faustinoaq** [comment]
> I find the extra cr's very annoying. I'm hoping we can remove them.

@drujensen Let me try using `<%-` instead of `-%>` 😅

**Comment by faustinoaq** [comment]
> @drujensen Let me try using <%- instead of -%> 😅

Adding both `<%-` and `-%>` solved the issue in an elegant way 🎉 

screenshot_20180202_110335

screenshot_20180202_110401

@drujensen No more ugly extra lines and trailing spaces 😄

**Comment by faustinoaq** [comment]
> ok, so this is a bug in slang?
>> I think so
> By removing the eol, this is a work around?
>> kinda

No more, Fixed now!!! 👍

**Comment by drujensen** [comment]
@faustinoaq Thanks for figuring that out!

**Comment by elorest** [comment]
Wasn't this merged before the last release?

**Comment by faustinoaq** [comment]
> Wasn't this merged before the last release?

@elorest No, wasn't. Issue #613 is still happening on `v0.6.5`

**Pull request merged**
