### PR TITLE
Simplifies render by removing edge case.

### PR DESCRIPTION
**Pull request by elorest**
### Description of the Change

Resolves issue: https://github.com/amberframework/amber/issues/790

Simplifies render by removing edge case, which is mostly only useful in specs. 

Still easily testable by passing in path param.

### Alternate Designs

Leave it how it is.

### Benefits

More straight forward with fewer magics to remember.

### Possible Drawbacks

Less magic, but more readable.

### CODE REVIEW

**Comment by faustinoaq** [comment]
@amberframework/contributors  @elorest Should we update [Layour Documentation](https://amberframework.gitbook.io/amber/guides/views#layouts) after this is merged?

**Comment by elorest** [comment]
@faustinoaq I just looked through them and it doesn't seem to change the existing docs. There are somethings in there that are wrong though that I need to fix. How do I access the current docs. Can I still edit the github docs project?

**Comment by faustinoaq** [comment]
> I just looked through them and it doesn't seem to change the existing docs. There are somethings in there that are wrong though that I need to fix. How do I access the current docs. Can I still edit the github docs project?

You can do both, edit directly on GitBook or use [amber docs repository](https://github.com/amberframework/docs)

**Comment by faustinoaq** [comment]
@damianham I think this change just broke modular recipe :sweat_smile: 

See: https://travis-ci.org/amberframework/recipes/jobs/383198970

**Comment by damianham** [comment]
Yes it did.  @elorest this change needs backing out so that people can continue to use the modular recipe.  An alternative is to modify amber_render_module and add render_template macro with the original macro implementation.

**Comment by faustinoaq** [comment]
> An alternative is to modify amber_render_module and add render_template macro with the original macro implementation.

I think we can do that as workaround, WDYT? :sweat_smile: 

This PR also conflicts with #808 /cc @elorest

**Comment by damianham** [comment]
merged the PR @faustinoaq thanks for your great work on everything

**Pull request merged**
