### PR TITLE
Use shards command with production flag

### PR DESCRIPTION
**Pull request by faustinoaq**
### Description of the Change

Add `--production` flag and avoid using `@crystal deps` , use `@shards install` instead

### Alternate Designs

No

### Benefits

Avoid running ameba when running `make` to build amber executable

### Possible Drawbacks

No

### CODE REVIEW

**Comment by faustinoaq** [comment]
@amberframework/core-team Some suggestions? :sweat_smile:

**Comment by marksiemers** [comment]
This seems fine to me, but I don't know enough about the differences between the two commands to approve.

**Comment by robacarp** [comment]
I'm in the same boat as @marksiemers.

**Comment by faustinoaq** [comment]
> This seems fine to me, but I don't know enough about the differences between the two commands to approve.

@marksiemers @robacarp `crystal deps` has been removed here https://github.com/crystal-lang/crystal/pull/5544

So, we should use `shards install` instead

Oh, and `--production` flag is to avoid installing ameba, because isn't needed here :sweat_smile:

**Pull request merged**
