### PR TITLE
Add method `Amber::Validators::Params#to_unsafe_h`

### PR DESCRIPTION
**Pull request by westonganger**
Solves #1042 

PR for documentation to be added after.

### CODE REVIEW

**Comment by drujensen** [comment]
needs at least one spec.

**Comment by westonganger** [comment]
Spec added

**Comment by drujensen** [comment]
I'm hesitant to add this since it is dangerous to allow unexpected params to be processed. I agree with the name of the method as `to_unsafe_h` but worried this may be abused and expose a way to bypass the safety net.

I am interested what @eliasjpr as well.

**Comment by eliasjpr** [comment]
Im fine with this. I would rather have people to call `raw_params.to_h` themselves.

**Comment by anamba** [comment]
Guess I'd better rename my own #to_unsafe_h to avoid clobbering this new one.

Perhaps I'll re-implement as a boolean flag to #to_h that would allow it to return the values of all declared params, even those that have not passed validation. I would use it to update the model object in memory, to populate the form after an invalid submission (the user shouldn't have to re-enter everything from scratch).

Let me know if that sounds useful and I can open a new PR.

**Pull request merged**
