### PR TITLE
initial pass at adding clear to amber

### PR DESCRIPTION
**Pull request by wontruefree**
### Description of the Change

This adds the ORM [clear](https://github.com/anykeyh/clear) to the generators.  Clear is an ORM built specifically for PostgreSQL in Crystal.  It offers a lot of features and is actively maintained.

### Benefits

Adding a new framework that is postgres specific and has a lot of super user features.

### Possible Drawbacks

This adds more cases to the generators and possibly more maintenance.

### CODE REVIEW

**Comment by wontruefree** [comment]
This is still very much a work in progress.  I am stuck though and wanted to see if anyone could help me.  I am getting conflicts in `shards install`.  This seems to be a conflict in transitive dependencies.  I can fork clear and just delete the dependency but obviously, it won't work as intended.  The dependency is not needed when interfacing with amber so it might not be a bad solution.

**Comment by robacarp** [comment]
@wontruefree clear is awesome! I think it'll be more maintainable to move this into an amber recipe instead of using the built in generators. Generally the effort with the built in generators is to simplify and reduce complexity, and to move as much as possible into a recipe.

**Comment by wontruefree** [comment]
I don't mind making this a recipe.
Is there any interest in the amber community in adding more ORMs?

**Comment by wontruefree** [comment]
@robacarp the initial problem with shards is now fixed.  But it seems like the amber team would rather this as a recipe right?

**Comment by robacarp** [comment]
@wontruefree yes, that way the amber generators don't have N complexity for N app skeletons and database managers

**Pull request closed without merging**
